openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier for the user.
        name:
          type: string
          description: The name of the user.
        email:
          type: string
          description: The email address of the user.
        age:
          type: integer
          description: The age of the user.
      required:
        - name
        - email
